### ISSUE TITLE
🐛  Google Forms connection failing 

### ISSUE THREAD

**Issue by BrainonSilicon** [aim-rsf/Glossary-of-Terms#39]
About
---

Currently the script that connects the google form responses and opens new Issues with suggested terms is failing. 

Is your task request related to a problem with the website or Glossary?
--- 

The issue is a GitHub API 403. 

What Needs to be Done
---

- Debug!

**Comment by BrainonSilicon** [comment]
Changing due date to end of February as it is a non-urgent task that won't block other work.

**Comment by RayStick** [comment]
When you get a chance, can you walk me through the steps to replicate the issue? And expand on the expected behavior? Then I can understand a little better, as I don't have any direct experience with GitHub Actions and Google Forms

**Comment by BrainonSilicon** [comment]
Let's do it tomorrow. We can use the session to document the bug properly.

**Comment by RayStick** [comment]
Sounds good to me!

**Comment by RayStick** [comment]
I think I have fixed it 🥳 
See [this issue](https://github.com/aim-rsf/Glossary-of-Terms/issues/65) which I just generated via google-form submission -> google-script -> github issue 
Definitely something to do with access token generation - we can discuss 1:1

**Comment by BrainonSilicon** [comment]
This is amazing @RayStick!! Thank you so much for looking in to it (and fixing it!!)

**Comment by RayStick** [comment]
@all-contributors please add @RayStick for bug fix

**Comment by RayStick** [comment]
@all-contributors please add @BrainonSilicon  for bug fix
